definitions:
  dtos.ProjectDto:
    properties:
      Description:
        type: string
      Name:
        type: string
      Options:
        description: Extra details
        type: string
      UserId:
        type: string
    required:
    - Name
    - UserId
    type: object
  dtos.UserLoginDto:
    properties:
      Email:
        type: string
      Password:
        type: string
    required:
    - Email
    - Password
    type: object
  dtos.UserSignupDto:
    properties:
      Email:
        type: string
      Name:
        type: string
      Password:
        minLength: 8
        type: string
    required:
    - Email
    - Name
    - Password
    type: object
  dtos.UserUpdateDto:
    properties:
      Email:
        type: string
      Name:
        type: string
      Password:
        minLength: 8
        type: string
    type: object
info:
  contact: {}
paths:
  /api/project:
    get:
      consumes:
      - application/json
      description: Retrieve all projects
      produces:
      - application/json
      responses: {}
      summary: List All Projects
      tags:
      - project
    post:
      consumes:
      - application/json
      description: Create a new project
      parameters:
      - description: Project Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.ProjectDto'
      produces:
      - application/json
      responses: {}
      summary: Create Project
      tags:
      - project
    put:
      consumes:
      - application/json
      description: Update existing project
      parameters:
      - description: Project Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.ProjectDto'
      produces:
      - application/json
      responses: {}
      summary: Update Project
      tags:
      - project
  /api/project/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a project by its ID
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Delete Project
      tags:
      - project
    get:
      consumes:
      - application/json
      description: Retrieve a project by its ID
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get Project by ID
      tags:
      - project
  /api/user:
    post:
      consumes:
      - application/json
      description: Register a new user account
      parameters:
      - description: Signup Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.UserSignupDto'
      produces:
      - application/json
      responses: {}
      summary: Sign Up User
      tags:
      - user
    put:
      consumes:
      - application/json
      description: Update existing user
      parameters:
      - description: User Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.UserUpdateDto'
      produces:
      - application/json
      responses: {}
      summary: Update User
      tags:
      - user
  /api/user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a user by its ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Delete User
      tags:
      - user
    get:
      consumes:
      - application/json
      description: Retrieve a user by its ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get User by ID
      tags:
      - user
  /api/user/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a JWT
      parameters:
      - description: Login Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.UserLoginDto'
      produces:
      - application/json
      responses: {}
      summary: Login User
      tags:
      - user
  /api/user/me:
    delete:
      consumes:
      - application/json
      description: Delete the authenticated user's account
      produces:
      - application/json
      responses: {}
      summary: Delete Current User
      tags:
      - user
    get:
      consumes:
      - application/json
      description: Retrieve the authenticated user's profile
      produces:
      - application/json
      responses: {}
      summary: Get Current User
      tags:
      - user
    put:
      consumes:
      - application/json
      description: Update the authenticated user's profile
      parameters:
      - description: User Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.UserUpdateDto'
      produces:
      - application/json
      responses: {}
      summary: Update Current User
      tags:
      - user
  /api/user/signup:
    post:
      consumes:
      - application/json
      description: Register a new user account
      parameters:
      - description: Signup Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.UserSignupDto'
      produces:
      - application/json
      responses: {}
      summary: Sign Up User
      tags:
      - user
swagger: "2.0"
